<?php


$_SESSION['ime']=mysqli_real_escape_string($conn,$_POST['ime']);
$_SESSION['prezime']=mysqli_real_escape_string($conn,$_POST['prezime']);

$_SESSION['predmet_11']=$_POST['predmet_11'];
$_SESSION['predmet_12']=$_POST['predmet_12'];
$_SESSION['predmet_13']=$_POST['predmet_13'];
$_SESSION['predmet_14']=$_POST['predmet_14'];
$_SESSION['predmet_15']=$_POST['predmet_15'];
$_SESSION['predmet_21']=$_POST['predmet_21'];
$_SESSION['predmet_22']=$_POST['predmet_22'];
$_SESSION['predmet_23']=$_POST['predmet_23'];
$_SESSION['predmet_24']=$_POST['predmet_24'];
$_SESSION['predmet_25']=$_POST['predmet_25'];
$_SESSION['predmet_31']=$_POST['predmet_31'];
$_SESSION['predmet_32']=$_POST['predmet_32'];
$_SESSION['predmet_33']=$_POST['predmet_33'];
$_SESSION['predmet_34']=$_POST['predmet_34'];
$_SESSION['predmet_35']=$_POST['predmet_35'];
$_SESSION['predmet_41']=$_POST['predmet_41'];
$_SESSION['predmet_42']=$_POST['predmet_42'];
$_SESSION['predmet_43']=$_POST['predmet_43'];
$_SESSION['predmet_44']=$_POST['predmet_44'];
$_SESSION['predmet_45']=$_POST['predmet_45'];
$_SESSION['predmet_51']=$_POST['predmet_51'];
$_SESSION['predmet_52']=$_POST['predmet_52'];
$_SESSION['predmet_53']=$_POST['predmet_53'];
$_SESSION['predmet_54']=$_POST['predmet_54'];
$_SESSION['predmet_55']=$_POST['predmet_55'];
$_SESSION['predmet_61']=$_POST['predmet_61'];
$_SESSION['predmet_62']=$_POST['predmet_62'];
$_SESSION['predmet_63']=$_POST['predmet_63'];
$_SESSION['predmet_64']=$_POST['predmet_64'];
$_SESSION['predmet_65']=$_POST['predmet_65'];
$_SESSION['predmet_71']=$_POST['predmet_71'];
$_SESSION['predmet_72']=$_POST['predmet_72'];
$_SESSION['predmet_73']=$_POST['predmet_73'];
$_SESSION['predmet_74']=$_POST['predmet_74'];
$_SESSION['predmet_75']=$_POST['predmet_75'];
$_SESSION['predmet_81']=$_POST['predmet_81'];
$_SESSION['predmet_82']=$_POST['predmet_82'];
$_SESSION['predmet_83']=$_POST['predmet_83'];
$_SESSION['predmet_84']=$_POST['predmet_84'];
$_SESSION['predmet_85']=$_POST['predmet_85'];


$_SESSION['odeljenje_11']=$_POST['odeljenje_11'];
$_SESSION['odeljenje_12']=$_POST['odeljenje_12'];
$_SESSION['odeljenje_13']=$_POST['odeljenje_13'];
$_SESSION['odeljenje_14']=$_POST['odeljenje_14'];
$_SESSION['odeljenje_15']=$_POST['odeljenje_15'];
$_SESSION['odeljenje_21']=$_POST['odeljenje_21'];
$_SESSION['odeljenje_22']=$_POST['odeljenje_22'];
$_SESSION['odeljenje_23']=$_POST['odeljenje_23'];
$_SESSION['odeljenje_24']=$_POST['odeljenje_24'];
$_SESSION['odeljenje_25']=$_POST['odeljenje_25'];
$_SESSION['odeljenje_31']=$_POST['odeljenje_31'];
$_SESSION['odeljenje_32']=$_POST['odeljenje_32'];
$_SESSION['odeljenje_33']=$_POST['odeljenje_33'];
$_SESSION['odeljenje_34']=$_POST['odeljenje_34'];
$_SESSION['odeljenje_35']=$_POST['odeljenje_35'];
$_SESSION['odeljenje_41']=$_POST['odeljenje_41'];
$_SESSION['odeljenje_42']=$_POST['odeljenje_42'];
$_SESSION['odeljenje_43']=$_POST['odeljenje_43'];
$_SESSION['odeljenje_44']=$_POST['odeljenje_44'];
$_SESSION['odeljenje_45']=$_POST['odeljenje_45'];
$_SESSION['odeljenje_51']=$_POST['odeljenje_51'];
$_SESSION['odeljenje_52']=$_POST['odeljenje_52'];
$_SESSION['odeljenje_53']=$_POST['odeljenje_53'];
$_SESSION['odeljenje_54']=$_POST['odeljenje_54'];
$_SESSION['odeljenje_55']=$_POST['odeljenje_55'];
$_SESSION['odeljenje_61']=$_POST['odeljenje_61'];
$_SESSION['odeljenje_62']=$_POST['odeljenje_62'];
$_SESSION['odeljenje_63']=$_POST['odeljenje_63'];
$_SESSION['odeljenje_64']=$_POST['odeljenje_64'];
$_SESSION['odeljenje_65']=$_POST['odeljenje_65'];
$_SESSION['odeljenje_71']=$_POST['odeljenje_71'];
$_SESSION['odeljenje_72']=$_POST['odeljenje_72'];
$_SESSION['odeljenje_73']=$_POST['odeljenje_73'];
$_SESSION['odeljenje_74']=$_POST['odeljenje_74'];
$_SESSION['odeljenje_75']=$_POST['odeljenje_75'];
$_SESSION['odeljenje_81']=$_POST['odeljenje_81'];
$_SESSION['odeljenje_82']=$_POST['odeljenje_82'];
$_SESSION['odeljenje_83']=$_POST['odeljenje_83'];
$_SESSION['odeljenje_84']=$_POST['odeljenje_84'];
$_SESSION['odeljenje_85']=$_POST['odeljenje_85'];



?>